-- MQC School Clinic Management System
-- Run this file in Supabase SQL Editor for the normalized schema.
-- clinic_state is retained for compatibility with the current snapshot API.

create extension if not exists "pgcrypto";

create table if not exists public.clinic_users (
  id text primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  name text not null,
  last_name text not null,
  first_name text not null,
  middle_initial text,
  role text not null check (role in ('Head Nurse & Administrator', 'Head Nurse', 'Staff Nurse')),
  username text not null unique,
  password_hash text,
  status text not null default 'Active' check (status in ('Active', 'Disabled')),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.patients (
  id text primary key,
  last_name text not null,
  first_name text not null,
  middle_initial text,
  name text not null,
  course text not null,
  year_level text not null,
  gender text,
  age integer check (age is null or age between 0 and 120),
  contact text,
  guardian_name text,
  guardian_contact text,
  allergies text default 'None known',
  medical_conditions text default 'None',
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.medicines (
  code text primary key,
  name text not null,
  category text not null default 'General',
  quantity integer not null default 0 check (quantity >= 0),
  unit text not null,
  batch_number text,
  expiration_date date,
  supplier text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipment (
  id text primary key,
  name text not null,
  quantity integer not null default 0 check (quantity >= 0),
  condition text not null default 'Good' check (condition in ('Good', 'Fair', 'Poor')),
  last_maintenance_date date,
  expiration_date date,
  status text not null default 'Available' check (status in ('Available', 'Under Maintenance', 'Damaged', 'Replacement Needed')),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.equipment add column if not exists expiration_date date;

create table if not exists public.clinical_visits (
  id text primary key,
  patient_id text not null references public.patients(id) on delete cascade,
  nurse_id text references public.clinic_users(id) on delete set null,
  nurse_name text not null,
  visit_date date not null,
  visit_time text not null,
  complaint text not null,
  description text,
  symptom_start text,
  pain_level text,
  pain_location text,
  symptoms jsonb not null default '[]'::jsonb,
  known_conditions text,
  allergies_history text,
  current_medication text,
  previous_similar text,
  last_meal text,
  weight text,
  height text,
  temperature text,
  blood_pressure text,
  heart_rate text,
  oxygen_saturation text,
  assessment text,
  assessment_other text,
  notes text,
  interventions jsonb not null default '[]'::jsonb,
  treatment_given text,
  medicine_code text references public.medicines(code) on delete set null,
  medicine_name text,
  medicine_quantity integer check (medicine_quantity is null or medicine_quantity > 0),
  dosage text,
  outcome text not null,
  released_at text,
  remarks text,
  guardian_contacted text,
  guardian_method text,
  person_contacted text,
  staff_record text,
  position text,
  status text not null default 'Active' check (status in ('Active', 'Superseded', 'Deleted')),
  version_of text,
  revision integer not null default 1,
  supersedes_id text,
  superseded_by text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade existing databases so deleting a patient also deletes that patient's visits.
alter table public.clinical_visits
  drop constraint if exists clinical_visits_patient_id_fkey;
alter table public.clinical_visits
  add constraint clinical_visits_patient_id_fkey
  foreign key (patient_id) references public.patients(id) on delete cascade;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id text references public.clinic_users(id) on delete set null,
  user_name text not null,
  action text not null,
  module text not null,
  status text not null default 'Success' check (status in ('Success', 'Warning', 'Error')),
  created_at timestamptz not null default now()
);

-- Development convenience: allow the app and the Supabase Table Editor to read and write
-- audit entries while the project is still establishing final auth policies.
drop policy if exists "audit_logs_all_access" on public.audit_logs;
create policy "audit_logs_all_access"
on public.audit_logs
for all
to authenticated, anon
using (true)
with check (true);

create table if not exists public.clinic_settings (
  id integer primary key default 1 check (id = 1),
  clinic_name text not null,
  address text,
  contact_number text,
  email text,
  clinic_open time,
  clinic_close time,
  clinic_days jsonb not null default '[]'::jsonb,
  patient_id_prefix text,
  low_stock_threshold integer not null default 15 check (low_stock_threshold >= 0),
  expiration_alert_days integer not null default 14 check (expiration_alert_days >= 0),
  password_min_length integer not null default 8 check (password_min_length > 0),
  session_timeout_minutes integer not null default 30 check (session_timeout_minutes > 0),
  date_format text not null default 'MMM D, YYYY',
  time_format text not null default '12-hour',
  timezone text not null default 'Asia/Manila',
  language text not null default 'English',
  updated_at timestamptz not null default now()
);

create table if not exists public.clinic_state (
  id integer primary key check (id = 1),
  state jsonb not null,
  updated_at timestamptz not null default now()
);

-- Marks the point at which normalized tables become the source of truth.
create table if not exists public.clinic_sync_meta (
  id integer primary key check (id = 1),
  normalized_ready boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.clinic_sync_meta (id, normalized_ready)
values (1, false)
on conflict (id) do nothing;

-- Keep modification times reliable for both the application and Supabase Table Editor.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists clinic_users_set_updated_at on public.clinic_users;
create trigger clinic_users_set_updated_at
before update on public.clinic_users
for each row execute function public.set_updated_at();

drop trigger if exists patients_set_updated_at on public.patients;
create trigger patients_set_updated_at
before update on public.patients
for each row execute function public.set_updated_at();

drop trigger if exists medicines_set_updated_at on public.medicines;
create trigger medicines_set_updated_at
before update on public.medicines
for each row execute function public.set_updated_at();

drop trigger if exists equipment_set_updated_at on public.equipment;
create trigger equipment_set_updated_at
before update on public.equipment
for each row execute function public.set_updated_at();

drop trigger if exists clinical_visits_set_updated_at on public.clinical_visits;
create trigger clinical_visits_set_updated_at
before update on public.clinical_visits
for each row execute function public.set_updated_at();

drop trigger if exists clinic_settings_set_updated_at on public.clinic_settings;
create trigger clinic_settings_set_updated_at
before update on public.clinic_settings
for each row execute function public.set_updated_at();

drop trigger if exists clinic_state_set_updated_at on public.clinic_state;
create trigger clinic_state_set_updated_at
before update on public.clinic_state
for each row execute function public.set_updated_at();

drop trigger if exists clinic_sync_meta_set_updated_at on public.clinic_sync_meta;
create trigger clinic_sync_meta_set_updated_at
before update on public.clinic_sync_meta
for each row execute function public.set_updated_at();

create index if not exists clinical_visits_patient_date_idx
  on public.clinical_visits (patient_id, visit_date desc);
create index if not exists clinical_visits_date_idx
  on public.clinical_visits (visit_date desc);
create index if not exists medicines_expiration_idx
  on public.medicines (expiration_date);
create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);

-- Keep tables private to server-side code until Supabase Auth policies are added.
alter table public.clinic_users enable row level security;

-- Local test account for the clinic login endpoint.
-- Change or remove this account before production use.
insert into public.clinic_users (
  id, name, last_name, first_name, role, username, password_hash, status
)
values (
  'NRS-TEST', 'Test Nurse', 'Nurse', 'Test', 'Staff Nurse', 'testnurse', extensions.crypt('test12345', extensions.gen_salt('bf')), 'Active'
)
on conflict (username) do update set
  name = excluded.name,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  role = excluded.role,
  password_hash = excluded.password_hash,
  status = excluded.status,
  updated_at = now();

-- Migrate clinic users already saved in the legacy browser snapshot.
insert into public.clinic_users (
  id,
  auth_user_id,
  name,
  last_name,
  first_name,
  middle_initial,
  role,
  username,
  status,
  deleted_at,
  updated_at
)
select
  nullif(user_row->>'id', ''),
  case
    when user_row->>'authUserId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    then (user_row->>'authUserId')::uuid
    else null
  end,
  coalesce(nullif(user_row->>'name', ''), concat_ws(', ', nullif(user_row->>'lastName', ''), nullif(user_row->>'firstName', ''))),
  coalesce(nullif(user_row->>'lastName', ''), split_part(user_row->>'name', ',', 1)),
  coalesce(nullif(user_row->>'firstName', ''), btrim(split_part(user_row->>'name', ',', 2))),
  nullif(user_row->>'middleInitial', ''),
  case when user_row->>'role' in ('Head Nurse & Administrator', 'Head Nurse', 'Staff Nurse') then user_row->>'role' else 'Staff Nurse' end,
  nullif(user_row->>'username', ''),
  case when user_row->>'status' = 'Disabled' then 'Disabled' else 'Active' end,
  case when coalesce((user_row->>'deleted')::boolean, false) then now() else null end,
  now()
from public.clinic_state as snapshots
cross join lateral jsonb_array_elements(coalesce(snapshots.state->'users', '[]'::jsonb)) as entries(user_row)
where snapshots.id = 1
  and nullif(user_row->>'id', '') is not null
  and nullif(user_row->>'username', '') is not null
  and coalesce(nullif(user_row->>'name', ''), concat_ws(', ', nullif(user_row->>'lastName', ''), nullif(user_row->>'firstName', ''))) is not null
  and nullif(user_row->>'lastName', '') is not null
  and nullif(user_row->>'firstName', '') is not null
on conflict (username) do update set
  auth_user_id = coalesce(excluded.auth_user_id, public.clinic_users.auth_user_id),
  name = excluded.name,
  last_name = excluded.last_name,
  first_name = excluded.first_name,
  middle_initial = excluded.middle_initial,
  role = excluded.role,
  status = excluded.status,
  deleted_at = excluded.deleted_at,
  updated_at = now();

update public.clinic_sync_meta
set normalized_ready = true,
    updated_at = now()
where id = 1
  and (
    not exists (
      select 1
      from public.clinic_state as snapshots
      cross join lateral jsonb_array_elements(coalesce(snapshots.state->'users', '[]'::jsonb)) as entries(user_row)
      where snapshots.id = 1
        and nullif(entries.user_row->>'username', '') is not null
    )
    or not exists (
      select 1
      from public.clinic_state as snapshots
      cross join lateral jsonb_array_elements(coalesce(snapshots.state->'users', '[]'::jsonb)) as entries(user_row)
      where snapshots.id = 1
        and nullif(entries.user_row->>'username', '') is not null
        and not exists (
          select 1
          from public.clinic_users as users
          where users.username = entries.user_row->>'username'
        )
    )
  );

-- Repair legacy audit rows when the old snapshot still contains a verifiable user ID.
-- To reset audit history once, run: delete from public.audit_logs;

update public.audit_logs as logs
set user_name = users.name
from public.clinic_users as users
where logs.user_id = users.id
  and lower(logs.user_name) = 'system';

update public.audit_logs as logs
set user_id = (
      select users.id
      from public.clinic_state as snapshots
      cross join lateral jsonb_array_elements(coalesce(snapshots.state->'auditLogs', '[]'::jsonb)) as entries(entry)
      join public.clinic_users as users on users.id = nullif(entries.entry->>'userId', '')
      where logs.action = entries.entry->>'action'
        and logs.module = entries.entry->>'module'
        and logs.created_at::date = to_date(entries.entry->>'date', 'YYYY-MM-DD')
      limit 1
    ),
    user_name = (
      select users.name
      from public.clinic_state as snapshots
      cross join lateral jsonb_array_elements(coalesce(snapshots.state->'auditLogs', '[]'::jsonb)) as entries(entry)
      join public.clinic_users as users on users.id = nullif(entries.entry->>'userId', '')
      where logs.action = entries.entry->>'action'
        and logs.module = entries.entry->>'module'
        and logs.created_at::date = to_date(entries.entry->>'date', 'YYYY-MM-DD')
      limit 1
    )
where logs.user_id is null
  and lower(logs.user_name) = 'system'
  and exists (
    select 1
    from public.clinic_state as snapshots
    cross join lateral jsonb_array_elements(coalesce(snapshots.state->'auditLogs', '[]'::jsonb)) as entries(entry)
    join public.clinic_users as users on users.id = nullif(entries.entry->>'userId', '')
    where logs.action = entries.entry->>'action'
      and logs.module = entries.entry->>'module'
      and logs.created_at::date = to_date(entries.entry->>'date', 'YYYY-MM-DD')
  );

-- Remove duplicate audit rows created by the old snapshot sync behavior.
with ranked_logs as (
  select
    id,
    row_number() over (
      partition by date_trunc('minute', created_at), coalesce(user_id, ''), user_name, action, module, status
      order by id
    ) as duplicate_rank
  from public.audit_logs
), duplicate_logs as (
  select id
  from ranked_logs
  where duplicate_rank > 1
)
delete from public.audit_logs as logs
using duplicate_logs
where logs.id = duplicate_logs.id;

create or replace function public.authenticate_clinic_user(p_username text, p_password text)
returns table (id text, name text, role text, username text, status text)
language sql
security definer
set search_path = public
as $$
  select id, name, role, username, status
  from public.clinic_users
  where username = p_username
    and status = 'Active'
    and password_hash is not null
    and extensions.crypt(p_password, password_hash) = password_hash;
$$;

revoke all on function public.authenticate_clinic_user(text, text) from public;
grant execute on function public.authenticate_clinic_user(text, text) to service_role;

alter table public.patients enable row level security;
alter table public.medicines enable row level security;
alter table public.equipment enable row level security;
alter table public.clinical_visits enable row level security;
alter table public.audit_logs enable row level security;
alter table public.clinic_settings enable row level security;
alter table public.clinic_state enable row level security;
alter table public.clinic_sync_meta enable row level security;