-- MQC School Clinic Management System
-- Run this file in Supabase SQL Editor for the normalized schema.
-- clinic_state is retained for compatibility with the current snapshot API.

create extension if not exists "pgcrypto";

create table if not exists public.clinic_users (
  id text primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  name text not null,
  last_name text not null,
  first_name text not null,
  middle_initial text,
  role text not null check (role in ('Head Nurse & Administrator', 'Head Nurse', 'Staff Nurse')),
  username text not null unique,
  password_hash text,
  status text not null default 'Active' check (status in ('Active', 'Disabled')),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.patients (
  id text primary key,
  last_name text not null,
  first_name text not null,
  middle_initial text,
  name text not null,
  course text not null,
  year_level text not null,
  gender text,
  age integer check (age is null or age between 0 and 120),
  contact text,
  guardian_name text,
  guardian_contact text,
  allergies text default 'None known',
  medical_conditions text default 'None',
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.medicines (
  code text primary key,
  name text not null,
  category text not null default 'General',
  quantity integer not null default 0 check (quantity >= 0),
  unit text not null,
  batch_number text,
  expiration_date date,
  supplier text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipment (
  id text primary key,
  name text not null,
  quantity integer not null default 0 check (quantity >= 0),
  condition text not null default 'Good' check (condition in ('Good', 'Fair', 'Poor')),
  last_maintenance_date date,
  status text not null default 'Available' check (status in ('Available', 'Under Maintenance', 'Damaged', 'Replacement Needed')),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clinical_visits (
  id text primary key,
  patient_id text not null references public.patients(id) on delete restrict,
  nurse_id text references public.clinic_users(id) on delete set null,
  nurse_name text not null,
  visit_date date not null,
  visit_time text not null,
  complaint text not null,
  description text,
  symptom_start text,
  pain_level text,
  pain_location text,
  symptoms jsonb not null default '[]'::jsonb,
  known_conditions text,
  allergies_history text,
  current_medication text,
  previous_similar text,
  last_meal text,
  weight text,
  height text,
  temperature text,
  blood_pressure text,
  heart_rate text,
  oxygen_saturation text,
  assessment text,
  assessment_other text,
  notes text,
  interventions jsonb not null default '[]'::jsonb,
  treatment_given text,
  medicine_code text references public.medicines(code) on delete set null,
  medicine_name text,
  medicine_quantity integer check (medicine_quantity is null or medicine_quantity > 0),
  dosage text,
  outcome text not null,
  released_at text,
  remarks text,
  guardian_contacted text,
  guardian_method text,
  person_contacted text,
  staff_record text,
  position text,
  status text not null default 'Active' check (status in ('Active', 'Superseded', 'Deleted')),
  version_of text,
  revision integer not null default 1,
  supersedes_id text,
  superseded_by text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id text references public.clinic_users(id) on delete set null,
  user_name text not null,
  action text not null,
  module text not null,
  status text not null default 'Success' check (status in ('Success', 'Warning', 'Error')),
  created_at timestamptz not null default now()
);

create table if not exists public.clinic_settings (
  id integer primary key default 1 check (id = 1),
  clinic_name text not null,
  address text,
  contact_number text,
  email text,
  clinic_open time,
  clinic_close time,
  clinic_days jsonb not null default '[]'::jsonb,
  patient_id_prefix text,
  low_stock_threshold integer not null default 15 check (low_stock_threshold >= 0),
  expiration_alert_days integer not null default 14 check (expiration_alert_days >= 0),
  password_min_length integer not null default 8 check (password_min_length > 0),
  session_timeout_minutes integer not null default 30 check (session_timeout_minutes > 0),
  date_format text not null default 'MMM D, YYYY',
  time_format text not null default '12-hour',
  timezone text not null default 'Asia/Manila',
  language text not null default 'English',
  updated_at timestamptz not null default now()
);

create table if not exists public.clinic_state (
  id integer primary key check (id = 1),
  state jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists clinical_visits_patient_date_idx
  on public.clinical_visits (patient_id, visit_date desc);
create index if not exists clinical_visits_date_idx
  on public.clinical_visits (visit_date desc);
create index if not exists medicines_expiration_idx
  on public.medicines (expiration_date);
create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);

-- Keep tables private to server-side code until Supabase Auth policies are added.
alter table public.clinic_users enable row level security;
alter table public.patients enable row level security;
alter table public.medicines enable row level security;
alter table public.equipment enable row level security;
alter table public.clinical_visits enable row level security;
alter table public.audit_logs enable row level security;
alter table public.clinic_settings enable row level security;
alter table public.clinic_state enable row level security;