import { sql } from "drizzle-orm";
import {
	bigserial,
	boolean,
	date,
	integer,
	jsonb,
	pgTable,
	check,
	text,
	time,
	timestamp,
	uniqueIndex,
	uuid,
} from "drizzle-orm/pg-core";

export const clinicUsersTable = pgTable(
	"clinic_users",
	{
		id: text("id").primaryKey(),
		authUserId: uuid("auth_user_id").unique(),
		name: text("name").notNull(),
		lastName: text("last_name").notNull(),
		firstName: text("first_name").notNull(),
		middleInitial: text("middle_initial"),
		role: text("role").notNull(),
		username: text("username").notNull(),
		passwordHash: text("password_hash"),
		status: text("status").notNull().default("Active"),
		deletedAt: timestamp("deleted_at", { withTimezone: true }),
		createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
		updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
	},
	(table) => [
		uniqueIndex("clinic_users_username_unique").on(table.username),
		check("clinic_users_role_check", sql`${table.role} in ('Head Nurse & Administrator', 'Head Nurse', 'Staff Nurse')`),
		check("clinic_users_status_check", sql`${table.status} in ('Active', 'Disabled')`),
	],
);

export const patientsTable = pgTable("patients", {
	id: text("id").primaryKey(),
	lastName: text("last_name").notNull(),
	firstName: text("first_name").notNull(),
	middleInitial: text("middle_initial"),
	name: text("name").notNull(),
	course: text("course").notNull(),
	yearLevel: text("year_level").notNull(),
	gender: text("gender"),
	age: integer("age"),
	contact: text("contact"),
	guardianName: text("guardian_name"),
	guardianContact: text("guardian_contact"),
	allergies: text("allergies").default("None known"),
	medicalConditions: text("medical_conditions").default("None"),
	deletedAt: timestamp("deleted_at", { withTimezone: true }),
	deletedBy: text("deleted_by"),
	createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const medicinesTable = pgTable("medicines", {
	code: text("code").primaryKey(),
	name: text("name").notNull(),
	category: text("category").notNull().default("General"),
	quantity: integer("quantity").notNull().default(0),
	unit: text("unit").notNull(),
	batchNumber: text("batch_number"),
	expirationDate: date("expiration_date"),
	supplier: text("supplier"),
	deletedAt: timestamp("deleted_at", { withTimezone: true }),
	createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const equipmentTable = pgTable("equipment", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	quantity: integer("quantity").notNull().default(0),
	condition: text("condition").notNull().default("Good"),
	lastMaintenanceDate: date("last_maintenance_date"),
	expirationDate: date("expiration_date"),
	status: text("status").notNull().default("Available"),
	deletedAt: timestamp("deleted_at", { withTimezone: true }),
	createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
	check("equipment_condition_check", sql`${table.condition} in ('Good', 'Fair', 'Poor')`),
	check("equipment_status_check", sql`${table.status} in ('Available', 'Under Maintenance', 'Damaged', 'Replacement Needed')`),
]);

export const clinicalVisitsTable = pgTable("clinical_visits", {
	id: text("id").primaryKey(),
	patientId: text("patient_id").notNull().references(() => patientsTable.id, { onDelete: "cascade" }),
	nurseId: text("nurse_id").references(() => clinicUsersTable.id),
	nurseName: text("nurse_name").notNull(),
	visitDate: date("visit_date").notNull(),
	visitTime: text("visit_time").notNull(),
	complaint: text("complaint").notNull(),
	description: text("description"),
	symptomStart: text("symptom_start"),
	painLevel: text("pain_level"),
	painLocation: text("pain_location"),
	symptoms: jsonb("symptoms").$type<string[]>().notNull().default([]),
	knownConditions: text("known_conditions"),
	allergiesHistory: text("allergies_history"),
	currentMedication: text("current_medication"),
	previousSimilar: text("previous_similar"),
	lastMeal: text("last_meal"),
	weight: text("weight"),
	height: text("height"),
	temperature: text("temperature"),
	bloodPressure: text("blood_pressure"),
	heartRate: text("heart_rate"),
	oxygenSaturation: text("oxygen_saturation"),
	assessment: text("assessment"),
	assessmentOther: text("assessment_other"),
	notes: text("notes"),
	interventions: jsonb("interventions").$type<string[]>().notNull().default([]),
	treatmentGiven: text("treatment_given"),
	medicineCode: text("medicine_code").references(() => medicinesTable.code),
	medicineName: text("medicine_name"),
	medicineQuantity: integer("medicine_quantity"),
	dosage: text("dosage"),
	outcome: text("outcome").notNull(),
	releasedAt: text("released_at"),
	remarks: text("remarks"),
	guardianContacted: text("guardian_contacted"),
	guardianMethod: text("guardian_method"),
	personContacted: text("person_contacted"),
	staffRecord: text("staff_record"),
	position: text("position"),
	status: text("status").notNull().default("Active"),
	versionOf: text("version_of"),
	revision: integer("revision").notNull().default(1),
	supersedesId: text("supersedes_id"),
	supersededBy: text("superseded_by"),
	deletedAt: timestamp("deleted_at", { withTimezone: true }),
	createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
	check("clinical_visits_status_check", sql`${table.status} in ('Active', 'Superseded', 'Deleted')`),
	check("clinical_visits_medicine_quantity_check", sql`${table.medicineQuantity} is null or ${table.medicineQuantity} > 0`),
]);

export const auditLogsTable = pgTable("audit_logs", {
	id: bigserial("id", { mode: "number" }).primaryKey(),
	userId: text("user_id").references(() => clinicUsersTable.id),
	userName: text("user_name").notNull(),
	action: text("action").notNull(),
	module: text("module").notNull(),
	status: text("status").notNull().default("Success"),
	createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
	check("audit_logs_status_check", sql`${table.status} in ('Success', 'Warning', 'Error')`),
]);

export const clinicSettingsTable = pgTable("clinic_settings", {
	id: integer("id").primaryKey().default(1),
	clinicName: text("clinic_name").notNull(),
	address: text("address"),
	contactNumber: text("contact_number"),
	email: text("email"),
	clinicOpen: time("clinic_open"),
	clinicClose: time("clinic_close"),
	clinicDays: jsonb("clinic_days").$type<string[]>().notNull().default([]),
	patientIdPrefix: text("patient_id_prefix"),
	lowStockThreshold: integer("low_stock_threshold").notNull().default(15),
	expirationAlertDays: integer("expiration_alert_days").notNull().default(14),
	passwordMinLength: integer("password_min_length").notNull().default(8),
	sessionTimeout: integer("session_timeout_minutes").notNull().default(30),
	dateFormat: text("date_format").notNull().default("MMM D, YYYY"),
	timeFormat: text("time_format").notNull().default("12-hour"),
	timezone: text("timezone").notNull().default("Asia/Manila"),
	language: text("language").notNull().default("English"),
	updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const clinicStateTable = pgTable("clinic_state", {
	id: integer("id").primaryKey(),
	state: jsonb("state").$type<Record<string, unknown>>().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const clinicSyncMetaTable = pgTable("clinic_sync_meta", {
	id: integer("id").primaryKey(),
	normalizedReady: boolean("normalized_ready").notNull().default(false),
	updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});